POST http://127.0.0.1:3000/api/portfolioCryptoPrice HTTP/1.1
content-type: application/json

{
    "dataPortfolio":["btc-bitcoin", "eth-ethereum"],
    "page": 1
}

###

GET http://127.0.0.1:3000/api/paginationCryptoPrice?category=cryptocurrency&page=2 HTTP/1.1


###
GET http://127.0.0.1:3000/api/cryptoGraph/?id=btc-bitcoin HTTP/1.1

### Search
GET http://127.0.0.1:3000/api/search/?id=bitcoin HTTP/1.1
